name: Build and deploy Python app to Azure Web App - amikomovie1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  AZURE_WEBAPP_NAME: 'amikomovie1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
          
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
          
      - name: Create deployment package
        run: |
          zip -r release.zip . \
            --exclude "venv/*" \
            --exclude "*.git*" \
            --exclude "*.pyc" \
            --exclude "__pycache__/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6FCF148A1E54FCCB470A760149B8D15 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9F4FBE55BC634A819825E202DBD07C85 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B842E5A07D1F45A18922F7F0DFDAAE29 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          startup-command: |
            gunicorn --bind=0.0.0.0 --timeout 600 your_project_name.wsgi:application
